{{-- resources/views/admin/allottee/sections/allotment-letter.blade.php --}}
<div>
    <!-- HEADER -->
    <div class="page-header">
        <div>
            <h1 class="page-title">
                Allotment Letter
            </h1>
            <p class="page-subtitle">
                Key information at a glance · Application
                {{ $allottee->application_no ?? 'JSHBA-24928374' }}
            </p>
        </div>
    </div>
    @php
        $allotmentLetter = \App\Models\AllotteeGeneratedDocument::where([
            'allottee_id' => $allottee->id,
            'document_type' => 'allotment-letter',
        ])
            ->latest()
            ->first();
    @endphp
    <div class="letter-hero letter-hero1">
        <p class="letter-hero-title">
            <i class="fa-solid fa-envelope-open-text me-2"></i>
            Allotment Letter
        </p>
        <p class="letter-hero-sub">
            @if ($allotmentLetter?->signed_file_path)
                Signed allotment letter uploaded successfully
            @elseif($allotmentLetter)
                Your allotment letter has been generated by system
            @else
                Allotment letter generation in progress
            @endif
        </p>
        <div class="app-no">
            {{ $allottee->application_no ?? '-' }}
        </div>
        <div
            style="
                display:flex;
                gap:10px;
                margin-top:18px;
                flex-wrap:wrap;
            ">
            @if ($allotmentLetter)
                {{-- VIEW GENERATED LETTER --}}
                <a href="{{ asset($allotmentLetter->file_path) }}" target="_blank" class="btn-brand"
                    style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                    <i class="fa-solid fa-eye"></i>
                    View Generated Copy
                </a>
                {{-- DOWNLOAD GENERATED LETTER --}}
                <a href="{{ asset($allotmentLetter->file_path) }}" download class="btn-brand"
                    style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                    <i class="fa-solid fa-download"></i>
                    Download Generated Copy
                </a>
                {{-- VIEW SIGNED COPY --}}
                @if ($allotmentLetter->signed_file_path)
                    <a href="{{ asset($allotmentLetter->signed_file_path) }}" target="_blank" class="btn-brand"
                        style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                        <i class="fa-solid fa-file-signature"></i>
                        View Signed Copy
                    </a>
                    {{-- DOWNLOAD SIGNED COPY --}}
                    <a href="{{ asset($allotmentLetter->signed_file_path) }}" download class="btn-brand"
                        style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                        <i class="fa-solid fa-download"></i>
                        Download Signed Copy
                    </a>
                @else
                    {{-- UPLOAD SIGNED COPY --}}
                    <a href="javascript:void(0)"
                        onclick="openReupload(
                            '{{ $allotmentLetter->document_name }}',
                            '{{ $allotmentLetter->document_type }}',
                            '{{ $allotmentLetter->id }}',
                            '{{ $allotmentLetter->allottee_id }}',
                            '{{ $step->step_no }}'
                        )"
                        class="btn-brand"
                        style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                        <i class="fa-solid fa-file-signature"></i>
                        Upload Signed Copy
                    </a>
                @endif
            @else
                <a href="{{ route('admin.allottees.letters.allotment.pdf', [
                    'allottee' => $allottee,
                    'download' => 1,
                ]) }}"
                    class="btn-brand"
                    style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                    <i class="fa-solid fa-file-pdf me-2"></i>
                    Generate Allotment Letter
                </a>
            @endif
        </div>
    </div>
</div>
