{{-- Aggreement Section --}}
{{-- HEADER --}}
<div class="page-header">
    <div>
        <h1 class="page-title"> Agreement </h1>
        <p class="page-subtitle">
            Agreement ·
            Application
            {{ $allottee->application_no ?? '-' }}
        </p>
    </div>

</div>

@php
$agreementDocument = \App\Models\AllotteeGeneratedDocument::where([
'allottee_id' => $allottee->id,
'document_type' => 'final-agreement-letter',
])
->latest()
->first();
@endphp

<div class="letter-hero letter-hero3">
    <p class="letter-hero-title">
        <i class="fa-solid fa-envelope-open-text me-2"></i>
        Agreement
    </p>
    <p class="letter-hero-sub">
        @if ($agreementDocument?->signed_file_path)
        Signed allotment letter uploaded successfully
        @elseif($agreementDocument)
        Your allotment letter has been generated by system
        @else
        Allotment letter generation in progress
        @endif
    </p>
    <div class="app-no">
        {{ $allottee->application_no ?? '-' }}
    </div>
    <div
        style="
                display:flex;
                gap:10px;
                margin-top:18px;
                flex-wrap:wrap;
            ">
        @if ($agreementDocument)
        {{-- VIEW SIGNED COPY --}}
        @if ($agreementDocument->signed_file_path)
        <a href="{{ route('media.document', ['path' => rtrim(config('app.doc_api_url', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($agreementDocument->signed_file_path, '/')]) }}" target="_blank" class="btn-brand"
            style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
            <i class="fa-solid fa-file-signature"></i>
            View Signed Copy
        </a>
        {{-- DOWNLOAD SIGNED COPY --}}
        <a href="{{ route('media.document', ['path' => rtrim(config('app.doc_api_url', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($agreementDocument->signed_file_path, '/')]) }}" target="_blank" class="btn-brand"
            style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
            <i class="fa-solid fa-download"></i>
            Download Signed Copy
        </a>
        @else
        <!-- {{-- VIEW GENERATED LETTER --}}
        <a href="{{ route('media.document', ['path' => rtrim(config('app.doc_api_url', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($agreementDocument->file_path, '/')]) }}" target="_blank" class="btn-brand"
            style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
            <i class="fa-solid fa-eye"></i>
            View Generated Agreement
        </a> -->
        {{-- DOWNLOAD GENERATED LETTER --}}
        <a href="{{ route('media.document', ['path' => rtrim(config('app.doc_api_url', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($agreementDocument->file_path, '/')]) }}" target="_blank" class="btn-brand"
            style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
            <i class="fa-solid fa-download"></i>
            Download Generated Agreement
        </a>

        @if (isset($pendingApplication) && $pendingApplication->currentStep && $pendingApplication->currentStep->step_code === 'agreement-allottee-upload')
        {{-- UPLOAD SIGNED COPY --}}
        <button type="button" class="btn-brand" style="background:#28a745; color:white; border: none;" onclick="openReuploadModal()">
            <i class="fa-solid fa-upload"></i>
            Upload Signed Agreement
        </button>

        <!-- Upload Signed Agreement Modal -->
        <div class="modal fade" id="reuploadConfirmModal" tabindex="-1" aria-labelledby="reuploadConfirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content" style="border-radius: 12px; border: none; box-shadow: 0 10px 30px rgba(0,0,0,0.1);">
                    <div class="modal-header" style="background: #f8f9fa; border-bottom: 1px solid #eaeaea; border-radius: 12px 12px 0 0;">
                        <h5 class="modal-title" id="reuploadConfirmModalLabel" style="font-weight: 600; color: #333;"><i class="fa-solid fa-file-signature text-primary me-2"></i> Upload Signed Agreement</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{{ route('allottee.applications.upload-signed-agreement', $pendingApplication->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body" style="padding: 20px;">
                            <div class="alert alert-warning" style="background: #fff3cd; border-color: #ffecb5; color: #664d03; border-radius: 8px;">
                                <strong><i class="fa-solid fa-circle-exclamation"></i> Instructions:</strong> Please download the generated agreement, sign it physically or digitally, and upload the scanned copy below.
                            </div>

                            <div class="mb-3 mt-4">
                                <label for="signed_agreement_file" class="form-label" style="font-weight: 600; color: #495057;">Select Signed File (PDF only) <span class="text-danger">*</span></label>
                                <input class="form-control" type="file" id="signed_agreement_file" name="signed_agreement_file" accept=".pdf" required style="padding: 10px; border-radius: 6px;">
                                <div class="form-text mt-2"><i class="fa-solid fa-circle-info text-info"></i> Max file size: 5MB. Ensure signatures are clearly visible.</div>
                            </div>
                        </div>
                        <div class="modal-footer" style="border-top: 1px solid #eaeaea;">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal" style="font-weight: 500; border-radius: 6px;">Cancel</button>
                            <button type="submit" class="btn btn-success" style="font-weight: 500; border-radius: 6px; background: #28a745;"><i class="fa-solid fa-cloud-arrow-up me-1"></i> Upload & Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <script>
            function openReuploadModal() {
                var myModal = new bootstrap.Modal(document.getElementById('reuploadConfirmModal'), {
                    keyboard: false
                });
                myModal.show();
            }
        </script>
        @endif
        @endif
        @else
        @if ($pendingApplication && $pendingApplication->application_type === 'agreement')
        {{-- APPLICATION PENDING --}}
        <button class="btn-brand" disabled style="background:#f1f5f9; color:#64748b; border:1px solid #cbd5e1; cursor:not-allowed;">
            <i class="fa-solid fa-spinner fa-spin"></i>
            Application In Progress
        </button>
        @else
        {{-- APPLY FOR AGREEMENT --}}
        <button type="button" class="btn-brand" style="background:rgba(255,255,255,.95); color:var(--brand);" onclick="openAgreementModal()">
            <i class="fa-solid fa-paper-plane"></i>
            Apply for Agreement Letter
        </button>

        <!-- Agreement Confirmation Modal -->
        <div class="modal fade" id="agreementConfirmModal" tabindex="-1" aria-labelledby="agreementConfirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content" style="border-radius: 12px; border: none; box-shadow: 0 10px 30px rgba(0,0,0,0.1);">
                    <div class="modal-header" style="background: #f8f9fa; border-bottom: 1px solid #eaeaea; border-radius: 12px 12px 0 0;">
                        <h5 class="modal-title" id="agreementConfirmModalLabel" style="font-weight: 600; color: #333;"><i class="fa-solid fa-file-contract text-primary me-2"></i> Apply for Agreement Letter</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" style="padding: 20px;">
                        <div class="alert alert-info" style="background: #e3f2fd; border-color: #b6d4fe; color: #084298; border-radius: 8px;">
                            <strong><i class="fa-solid fa-circle-info"></i> Information:</strong> You are about to initiate the Agreement application process.
                        </div>
                        <h6 style="font-weight: 600; margin-top: 15px; color: #495057;">Processing Time</h6>
                        <p style="font-size: 14px; color: #6c757d; margin-bottom: 15px;"><i class="fa-regular fa-clock me-1"></i> Typically takes <strong>7-15 working days</strong> for the department to process and generate your agreement letter.</p>

                        <h6 style="font-weight: 600; color: #495057;">Required Documents (if requested later)</h6>
                        <ul style="font-size: 14px; color: #6c757d; padding-left: 20px; margin-bottom: 20px;">
                            <li>Aadhar Card / PAN Card copy</li>
                            <li>Passport size photographs</li>
                            <li>Income Certificate (if applicable)</li>
                            <li>Payment receipts of initial deposit</li>
                        </ul>

                        <p style="font-size: 14px; color: #333; font-weight: 500; margin-bottom: 0;">Are you sure you want to apply for the Agreement Letter now?</p>
                    </div>
                    <div class="modal-footer" style="border-top: 1px solid #eaeaea;">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal" style="font-weight: 500; border-radius: 6px;">Cancel</button>
                        <form action="{{ route('allottee.apply.application') }}" method="POST" class="d-inline">
                            @csrf
                            <input type="hidden" name="application_type" value="agreement">
                            <button type="submit" class="btn btn-primary" style="font-weight: 500; border-radius: 6px;"><i class="fa-solid fa-check-circle me-1"></i> Confirm & Apply</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <script>
            function openAgreementModal() {
                var myModal = new bootstrap.Modal(document.getElementById('agreementConfirmModal'), {
                    keyboard: false
                });
                myModal.show();
            }
        </script>
        @endif
        @endif
    </div>
</div>