{{-- Possession Letter Section --}}
{{-- HEADER --}}
<div class="page-header">
    <div>
        <h1 class="page-title"> Possession Letter </h1>
        <p class="page-subtitle">
            Possession Letter ·
            Application
            {{ $allottee->application_no ?? '-' }}
        </p>
    </div>

</div>

@php
$possessionLetter = \App\Models\AllotteeGeneratedDocument::where([
'allottee_id' => $allottee->id,
'document_type' => 'possession-letter',
])
->latest()
->first();
@endphp

<div class="letter-hero letter-hero2">
    <p class="letter-hero-title">
        <i class="fa-solid fa-envelope-open-text me-2"></i>
        Possession Letter
    </p>
    <p class="letter-hero-sub">
        @if ($possessionLetter?->signed_file_path)
        Signed allotment letter uploaded successfully
        @elseif($possessionLetter)
        Your allotment letter has been generated by system
        @else
        Allotment letter generation in progress
        @endif
    </p>
    <div class="app-no">
        {{ $allottee->application_no ?? '-' }}
    </div>
    <div
        style="
                display:flex;
                gap:10px;
                margin-top:18px;
                flex-wrap:wrap;
            ">
        @php
            $agreementDoc = \App\Models\AllotteeGeneratedDocument::where([
                'allottee_id' => $allottee->id,
                'document_type' => 'final-agreement-letter',
            ])->latest()->first();
            
            $hasStampedAgreement = $agreementDoc ? true : false;
        @endphp
        @if ($possessionLetter)
        {{-- VIEW GENERATED LETTER --}}
        <a href="{{ rtrim(env('DOC_API_URL', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($possessionLetter->file_path, '/') }}" target="_blank" class="btn-brand"
            style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
            <i class="fa-solid fa-eye"></i>
            View Generated Copy
        </a>
        {{-- DOWNLOAD GENERATED LETTER --}}
        <a href="{{ rtrim(env('DOC_API_URL', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($possessionLetter->file_path, '/') }}" download class="btn-brand"
            style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
            <i class="fa-solid fa-download"></i>
            Download Generated Copy
        </a>
        {{-- VIEW SIGNED COPY --}}
        @if ($possessionLetter->signed_file_path)
        <a href="{{ rtrim(env('DOC_API_URL', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($possessionLetter->signed_file_path, '/') }}" target="_blank" class="btn-brand"
            style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
            <i class="fa-solid fa-file-signature"></i>
            View Signed Copy
        </a>
        {{-- DOWNLOAD SIGNED COPY --}}
        <a href="{{ rtrim(env('DOC_API_URL', 'http://localhost/jshb-doc'), '/') . '/' . ltrim($possessionLetter->signed_file_path, '/') }}" download class="btn-brand"
            style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
            <i class="fa-solid fa-download"></i>
            Download Signed Copy
        </a>
        @else
        {{-- UPLOAD SIGNED COPY --}}
        <a href="javascript:void(0)"
            onclick="openReupload(
                            '{{ $possessionLetter->document_name }}',
                            '{{ $possessionLetter->document_type }}',
                            '{{ $possessionLetter->id }}',
                            '{{ $possessionLetter->allottee_id }}',
                            '{{ $step->step_no }}'
                        )"
            class="btn-brand"
            style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
            <i class="fa-solid fa-file-signature"></i>
            Upload Signed Copy
        </a>
        @endif
        @else
        @if ($pendingApplication && $pendingApplication->application_type === 'possession')
        {{-- APPLICATION PENDING --}}
        <button class="btn-brand" disabled style="background:#f1f5f9; color:#64748b; border:1px solid #cbd5e1; cursor:not-allowed;">
            <i class="fa-solid fa-spinner fa-spin"></i>
            Application In Progress
        </button>
        @else
        @if($hasStampedAgreement)
        <button type="button" class="btn-brand" style="background:rgba(255,255,255,.95); color:var(--brand);" onclick="openPossessionModal()">
            <i class="fa-solid fa-paper-plane"></i>
            Apply for Possession Letter
        </button>
        @else
        <button type="button" class="btn-brand" disabled style="background:#f1f5f9; color:#64748b; border:1px solid #cbd5e1; cursor:not-allowed;" title="Signed Agreement required to apply">
            <i class="fa-solid fa-ban"></i>
            Apply for Possession Letter
        </button>
        @endif

        <!-- Possession Confirmation Modal -->
        <div class="modal fade" id="possessionConfirmModal" tabindex="-1" aria-labelledby="possessionConfirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content" style="border-radius: 12px; border: none; box-shadow: 0 10px 30px rgba(0,0,0,0.1);">
                    <div class="modal-header" style="background: #f8f9fa; border-bottom: 1px solid #eaeaea; border-radius: 12px 12px 0 0;">
                        <h5 class="modal-title" id="possessionConfirmModalLabel" style="font-weight: 600; color: #333;"><i class="fa-solid fa-key text-primary me-2"></i> Apply for Possession Letter</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{{ route('allottee.apply.application') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="application_type" value="possession">
                        <div class="modal-body" style="padding: 20px;">
                            <div class="alert alert-info" style="background: #e3f2fd; border-color: #b6d4fe; color: #084298; border-radius: 8px;">
                                <strong><i class="fa-solid fa-circle-info"></i> Information:</strong> You are about to initiate the Possession application process.
                            </div>
                            
                            <h6 style="font-weight: 600; margin-top: 15px; color: #495057;">Stamped Agreement Requirement</h6>
                            <p style="font-size: 14px; color: #6c757d; margin-bottom: 15px;">A stamped agreement is mandatory for this application.</p>
                            
                            <div class="form-check mb-3">
                                <input class="form-check-input" type="checkbox" id="use_existing_agreement" name="use_existing_agreement" value="1" required>
                                <label class="form-check-label" for="use_existing_agreement" style="font-weight: 500; color: #333;">
                                    I confirm to use my existing generated stamped agreement document
                                </label>
                            </div>
                            
                            <p style="font-size: 14px; color: #333; font-weight: 500; margin-bottom: 0;">Are you sure you want to apply for the Possession Letter now?</p>
                        </div>
                        <div class="modal-footer" style="border-top: 1px solid #eaeaea;">
                            <button type="button" class="btn btn-light" data-bs-dismiss="modal" style="font-weight: 500; border-radius: 6px;">Cancel</button>
                            <button type="submit" class="btn btn-primary" style="font-weight: 500; border-radius: 6px;"><i class="fa-solid fa-check-circle me-1"></i> Confirm & Apply</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        
        <script>
            function openPossessionModal() {
                var myModal = new bootstrap.Modal(document.getElementById('possessionConfirmModal'), {
                    keyboard: false
                });
                myModal.show();
            }
        </script>
        @endif
        @endif
    </div>
</div>
