{{-- Possession Letter Section --}}
{{-- HEADER --}}
<div class="page-header">
    <div>
        <h1 class="page-title"> Possession Letter </h1>
        <p class="page-subtitle">
            Possession Letter ·
            Application
            {{ $allottee->application_no ?? '-' }}
        </p>
    </div>
    <button class="btn-ghost" onclick="window.close();"> <i class="fa-solid fa-arrow-left"></i> Back to List </button>
</div>

@php
    $possessionLetter = \App\Models\AllotteeGeneratedDocument::where([
        'allottee_id' => $allottee->id,
        'document_type' => 'possession-letter',
    ])
        ->latest()
        ->first();
@endphp

<div class="letter-hero letter-hero2">
    <p class="letter-hero-title">
        <i class="fa-solid fa-envelope-open-text me-2"></i>
        Possession Letter
    </p>
    <p class="letter-hero-sub">
        @if ($possessionLetter?->signed_file_path)
            Signed allotment letter uploaded successfully
        @elseif($possessionLetter)
            Your allotment letter has been generated by system
        @else
            Allotment letter generation in progress
        @endif
    </p>
    <div class="app-no">
        {{ $allottee->application_no ?? '-' }}
    </div>
    <div
        style="
                display:flex;
                gap:10px;
                margin-top:18px;
                flex-wrap:wrap;
            ">
        @if ($possessionLetter)
            {{-- VIEW GENERATED LETTER --}}
            <a href="{{ asset($possessionLetter->file_path) }}" target="_blank" class="btn-brand"
                style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                <i class="fa-solid fa-eye"></i>
                View Generated Copy
            </a>
            {{-- DOWNLOAD GENERATED LETTER --}}
            <a href="{{ asset($possessionLetter->file_path) }}" download class="btn-brand"
                style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                <i class="fa-solid fa-download"></i>
                Download Generated Copy
            </a>
            {{-- VIEW SIGNED COPY --}}
            @if ($possessionLetter->signed_file_path)
                <a href="{{ asset($possessionLetter->signed_file_path) }}" target="_blank" class="btn-brand"
                    style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                    <i class="fa-solid fa-file-signature"></i>
                    View Signed Copy
                </a>
                {{-- DOWNLOAD SIGNED COPY --}}
                <a href="{{ asset($possessionLetter->signed_file_path) }}" download class="btn-brand"
                    style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                    <i class="fa-solid fa-download"></i>
                    Download Signed Copy
                </a>
            @else
                {{-- UPLOAD SIGNED COPY --}}
                <a href="javascript:void(0)"
                    onclick="openReupload(
                            '{{ $possessionLetter->document_name }}',
                            '{{ $possessionLetter->document_type }}',
                            '{{ $possessionLetter->id }}',
                            '{{ $possessionLetter->allottee_id }}',
                            '{{ $step->step_no }}'
                        )"
                    class="btn-brand"
                    style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                    <i class="fa-solid fa-file-signature"></i>
                    Upload Signed Copy
                </a>
            @endif
        @else
            {{-- <button class="btn-brand" disabled
                style="
                        background:rgba(255,255,255,.2);
                        opacity:0.7;
                    ">
                <i class="fa-solid fa-clock"></i>
                Waiting For Generation
            </button> --}}

            <a href="{{ route('admin.allottees.letters.possession.pdf', [
                'allottee' => $allottee,
                'download' => 1,
            ]) }}"
                class="btn-brand"
                style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                <i class="fa-solid fa-file-pdf me-2"></i>
                Generate Possession Letter
            </a>
        @endif
    </div>
</div>
