{{-- Aggreement Section --}}
{{-- HEADER --}}
<div class="page-header">
    <div>
        <h1 class="page-title"> Agreement </h1>
        <p class="page-subtitle">
            Agreement ·
            Application
            {{ $allottee->application_no ?? '-' }}
        </p>
    </div>
    <button class="btn-ghost" onclick="window.close();"> <i class="fa-solid fa-arrow-left"></i> Back to List </button>
</div>

@php
    $agreementDocument = \App\Models\AllotteeGeneratedDocument::where([
        'allottee_id' => $allottee->id,
        'document_type' => 'agreement',
    ])
        ->latest()
        ->first();
@endphp

<div class="letter-hero letter-hero3">
    <p class="letter-hero-title">
        <i class="fa-solid fa-envelope-open-text me-2"></i>
        Agreement
    </p>
    <p class="letter-hero-sub">
        @if ($agreementDocument?->signed_file_path)
            Signed allotment letter uploaded successfully
        @elseif($agreementDocument)
            Your allotment letter has been generated by system
        @else
            Allotment letter generation in progress
        @endif
    </p>
    <div class="app-no">
        {{ $allottee->application_no ?? '-' }}
    </div>
    <div
        style="
                display:flex;
                gap:10px;
                margin-top:18px;
                flex-wrap:wrap;
            ">
        @if ($agreementDocument)
            {{-- VIEW SIGNED COPY --}}
            @if ($agreementDocument->signed_file_path)
                <a href="{{ asset($agreementDocument->signed_file_path) }}" target="_blank" class="btn-brand"
                    style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                    <i class="fa-solid fa-file-signature"></i>
                    View Signed Copy
                </a>
                {{-- DOWNLOAD SIGNED COPY --}}
                <a href="{{ asset($agreementDocument->signed_file_path) }}" download class="btn-brand"
                    style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                    <i class="fa-solid fa-download"></i>
                    Download Signed Copy
                </a>
            @else
                {{-- VIEW UPLOAD LETTER --}}
                <a href="{{ asset($agreementDocument->file_path) }}" target="_blank" class="btn-brand"
                    style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                    <i class="fa-solid fa-eye"></i>
                    View Uploaded Copy
                </a>
                {{-- DOWNLOAD UPLOAD LETTER --}}
                <a href="{{ asset($agreementDocument->file_path) }}" download class="btn-brand"
                    style="
                        background:rgba(255,255,255,.95);
                        color:var(--brand);
                    ">
                    <i class="fa-solid fa-download"></i>
                    Download Uploaded Copy
                </a>
            @endif
        @else
            {{-- UPLOAD SIGNED COPY --}}
            <a href="javascript:void(0)"
                onclick="openReupload(
                            'Agreement',
                            'agreement',
                            'up',
                            '{{ $allottee->id }}',
                            '{{ $step->step_no }}'
                        )"
                class="btn-brand"
                style="
                            background:rgba(255,255,255,.95);
                            color:var(--brand);
                        ">
                <i class="fa-solid fa-file-signature"></i>
                Upload Agreement
            </a>
        @endif
    </div>
</div>
